### ISSUE TITLE
Error while generating a PDF.

### ISSUE THREAD

**Issue by brynnflynn** [cfcurtis/pdfstitcher#207]
## Steps to reproduce the problem

1. Open the pattern
2. Select just layer 6
3. Generate the PDF

## Program Output
```
Could not detect system language, defaulting to English
Opening M:\Users\smith\Downloads\Auroras_Girls (3).pdf
PDF file loaded without errors.
Please be respectful of the author and only use this tool for personal use.
File will be written to M:\Users\smith\Downloads\Auroras_Girls_2024.pdf
Something went wrong
Traceback (most recent call last):
  File "pdfstitcher\layerfilter.py", line 571, in filter_content
  File "pikepdf\_methods.py", line 367, in make_stream
  File "pikepdf\objects.py", line 286, in __new__
TypeError: Must make Stream from binary data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pdfstitcher\ui\main_frame.py", line 191, in on_go_pressed
  File "pdfstitcher\layerfilter.py", line 380, in run
  File "pdfstitcher\layerfilter.py", line 576, in filter_content
UnboundLocalError: local variable '_' referenced before assignment
```

## Current Configuration
```
general:
  check_updates: true
  language: en
  margin: '0'
  open_dir: M:\Users\smith\Downloads
  save_dir: M:\Users\smith\Downloads
  units: !units 'INCHES'
line_props:
  colour:
    enable: true
    fill: false
    value: !!python/tuple
    - 0
    - 0
    - 0
  style:
    enable: true
    value: 0
  thickness:
    enable: true
    units: !units 'POINTS'
    value: '4'
```

## System Info
```
architecture: AMD64
pdfstitcher-version: 0.9.2
platform: Windows
platform-release: '10'
platform-version: 10.0.19043
processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
python-build: !!python/tuple
- tags/v3.8.10:3d8993a
- May  3 2021 11:48:03
python-implementation: CPython
python-version: 3.8.10
ram: 64 GB
```

**Comment by brynnflynn** [comment]
Downgrading to version 0.9.1 fixed the issue.

```
Opening M:\Users\smith\Downloads\Auroras_Girls (3).pdf
PDF file loaded without errors.
Please be respectful of the author and only use this tool for personal use.
File will be written to M:\Users\smith\Downloads\Auroras_Girls_size_5.pdf
Failed writing stream to page with error type <class 'TypeError'>
Warning: The pages {33, 44, 46} have a different size than the page before
Tiling with 7 rows and 7 columns
Options:
    Margins: 0.0 in
    Trim: [0, 0, 0, 0] in
    Rotation: None
    Page order: Rows then columns, Left to right, Top to bottom
    Vertical alignment: Bottom
    Horizontal alignment: Left
Output size: 77.00 x 74.54 in
Tiling successful
Successfully written to M:\Users\smith\Downloads\Auroras_Girls_size_5.pdf
```

**Comment by cfcurtis** [comment]
Thank you for the detailed report, I'll look in to why it's not behaving in 0.9.2. Is it just this document, or is it failing for all PDFs in 0.9.2?

It looks like there's still something weird happening in 0.9.1 ("Failed writing stream to page with error type <class 'TypeError'>") so I'm wondering if there's an edge case in this document that I'm not handling correctly.

**Comment by brynnflynn** [comment]
It must be an edge case in the document--I tried another PDF and it worked flawlessly. Would sending the mangled PDF help?

**Comment by brynnflynn** [comment]
[7ec8f02b4146b18d8ec2f86f058dbbe8.pdf](https://github.com/cfcurtis/pdfstitcher/files/14115148/7ec8f02b4146b18d8ec2f86f058dbbe8.pdf)

**Comment by cfcurtis** [comment]
Unable to replicate with pikepdf 8.15.1, I'm guessing it was fixed upstream.
